name: CICD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on your project's requirements
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ali769/nodejs:latest .
      - name: Publish image to Docker Hub
        run: docker push ali769/nodejs:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Adjust to match your EC2 runner on awsw
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from Docker Hub
        run: docker pull ali769/nodejs:latest
      - name: Delete old container (if exists)
        run: docker rm -f nodejs-app-container || true
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name nodejs-app-container ali769/nodejs:latest